server:
    servlet:
        context-path: /demo
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/empdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: root
        password: root
